### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by Quinten** [mnpk/vim-jira-complete#13]
When i hit `F5` in insert-mode when i am in my fugitive commit window i get

```
Error detected while processing function jira#_init_python:
line   12:
Traceback (most recent call last):
Error detected while processing function jira#_init_python:
line   12:
  File "<string>", line 1, in <module>
Error detected while processing function jira#_init_python:
line   12:
  File "/Users/quinten/.vim/bundle/vim-jira-complete/py/vimjira.py", line 12, in <module>
Error detected while processing function jira#_init_python:
line   12:
    import requests
Error detected while processing function jira#_init_python:
line   12:
ImportError: No module named requests
Error detected while processing function jira#_complete[1]..jira#get_issues[2]..jira#_do_fetch_issues[2]..jira#_init_python:
line   12:
Traceback (most recent call last):
Error detected while processing function jira#_complete[1]..jira#get_issues[2]..jira#_do_fetch_issues[2]..jira#_init_python:
line   12:
  File "<string>", line 1, in <module>
Error detected while processing function jira#_complete[1]..jira#get_issues[2]..jira#_do_fetch_issues[2]..jira#_init_python:
line   12:
  File "/Users/quinten/.vim/bundle/vim-jira-complete/py/vimjira.py", line 12, in <module>
Error detected while processing function jira#_complete[1]..jira#get_issues[2]..jira#_do_fetch_issues[2]..jira#_init_python:
line   12:
    import requests
Error detected while processing function jira#_complete[1]..jira#get_issues[2]..jira#_do_fetch_issues[2]..jira#_init_python:
line   12:
ImportError: No module named requests
```

However i did run

`pip install requests`

after i installed python with homebrew.

Still the error remains.

**Comment by schtibe** [comment]
If it helps: I had the same errors, and had to make sure that `requests` is installed for python 2. I don't know how to do that with homebrew though...

**Comment by Chebotarev** [comment]
I had the same error, managed to resolve it by installing `requests` with the following:

```
pip2 install requests
```
